config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'events#index'
  resources :events
  put 'complete_event', to: 'events#complete'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :bigint(8)        not null, primary key
#  title          :string           not null
#  tags           :string
#  scheduled_date :datetime         not null
#  user_id        :integer
#  completed      :boolean          default(FALSE), not null
#

class Event < ActiveRecord::Base
  self.table_name = 'events'

  validates_presence_of :title, :scheduled_date
  validates_inclusion_of :completed, in: [true, false]

  belongs_to :user, foreign_key: :user_id, class_name: 'User'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string
#  password               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  self.table_name = 'users'

  has_many :events, foreign_key: :user_id, class_name: 'Event'

  validates_presence_of :email, :password

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    user = User.create(email: data['email'], password: Devise.friendly_token[0,20]) unless user
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def new
    @event = current_user.events.new
  end

  def create
    @event = current_user.events.create(event_params)
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def index
    @events = if search_params[:term]
                current_user.events.where('title LIKE ?', "%#{search_params[:term]}%")
              else
                current_user.events
              end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path
    else
      render 'edit'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to events_path
  end

  def complete
    current_user.events.find(params[:id]).update!(completed: true)
    redirect_to events_path
  end

  private

  def search_params
    params.permit(:term)
  end

  def event_params
    params.require(:event).permit(:title, :scheduled_date, :tags, :term)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= simple_form_for event do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %>errors:</h2>
      <ul>
        <% event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title, size: 20 %>
  <%= f.input :tags %>
  <%= f.input :scheduled_date %>
  <%= f.button :submit, class: 'btn-primary' %>

<% end %>
<br>
<%= link_to "Back", events_path %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<table class="table">
  <% if @events.any? %>
    <tr>
      <th>Title</th>
      <th>List of Tags</th>
      <th>Scheduled Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <!-- TODO scope events to user-->
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.tags %></td>
        <td><%= event.scheduled_date.strftime('%d-%m-%Y %H:%M') %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Delete', event_path(event),
                        method: :delete,
                        data: {confirm: 'Are you sure?'} %></td>
        <td>
          <% if event.completed? %>
            Completed
          <% else %>
            <%= link_to 'Complete', complete_event_path(id: event.id),
                        method: :put,
                        data: {confirm: 'Are you sure?'} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events Calendar</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="col-sm-8">
    <div class="navs">
      <div class="row">
        <% if current_user %>
          <div class="col-sm-6">
            <%= form_tag(events_path, method: :get) do %>
              <%= text_field_tag :term, params[:term] %>
              <%= submit_tag 'Search', class: 'btn-secondary' %>
            <% end %>
          </div>
          <div class="col-sm-6">
            <%= link_to "Sign Out", destroy_user_session_path %> |
            <%= current_user.email %> |
            <%= link_to "New Event", new_event_path %>
          </div>
        <% else %>
          <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>
        <% end %>
      </div>
    </div>
    <br>
    <%= yield %>
  </div>
</div>

</body>
</html>